# Generated by Django 2.1.7 on 2019-06-10 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0003_auto_20190610_0139'),
    ]

    operations = [
        migrations.AlterField(
            model_name='simulation',
            name='title',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
