# Generated by Django 2.1.7 on 2019-06-24 12:38

import app1.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0004_auto_20190610_0225'),
    ]

    operations = [
        migrations.CreateModel(
            name='machine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, null=True)),
                ('hersteller', models.CharField(max_length=50, null=True)),
                ('modellnummer', models.CharField(max_length=50, null=True)),
                ('records', models.FileField(upload_to='app1/machines/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['csv', 'tsv', 'xslx'])], verbose_name='records (.xslx)')),
                ('tables', models.FileField(upload_to=app1.models.machine_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['csv', 'tsv', 'xslx'])], verbose_name='tables (.xslx)')),
            ],
        ),
    ]
