# Generated by Django 2.1.7 on 2019-06-24 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0005_machine'),
    ]

    operations = [
        migrations.AddField(
            model_name='machine',
            name='maschinentyp',
            field=models.CharField(choices=[('1', 'Elektrokessel'), ('3', 'Heizkessel'), ('3', 'Pufferspeicher'), ('4', 'Blockheizkraftwerk')], max_length=50, null=True),
        ),
    ]
