# Generated by Django 2.1.7 on 2019-06-24 12:55

import app1.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0006_machine_maschinentyp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='machine',
            name='records',
            field=models.FileField(upload_to='app1/machines/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['csv', 'tsv', 'xlsx'])], verbose_name='records (.xslx)'),
        ),
        migrations.AlterField(
            model_name='machine',
            name='tables',
            field=models.FileField(upload_to=app1.models.machine_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['csv', 'tsv', 'xlsx'])], verbose_name='tables (.xslx)'),
        ),
    ]
